In [5]:
import pandas as pd

In [7]:
df = pd.read_csv('/content/crop_yield.csv')

In [6]:
import numpy as np

In [ ]:
yield_array = np.array(df['Yield'])
print(yield_array)

[ 0.79608696  0.71043478  0.23833333 ...  0.7375      0.82454545
 26.19809524]


In [ ]:
np.mean(yield_array)

np.float64(201.42448210407485)

In [ ]:
np.max(yield_array)

np.float64(13592.12778)

In [ ]:
np.min(yield_array)

np.float64(0.0)

In [ ]:
rainfall_array = np.array(df['Annual_Rainfall'])
print(rainfall_array)

[2051.4 2051.4 2051.4 ...  845.2  845.2  845.2]


In [ ]:
production_array = np.array(df['Production'])
print(production_array)

[  56708    4685      22 ...   39988    6986 1224106]


In [ ]:
area_array = np.array(df['Area'])
print(area_array)

[73814  6637   796 ... 48995 12081 50286]


In [ ]:
print("Yield Standard Deviation:", round(np.std(yield_array), 2))

Yield Standard Deviation: 1318.9


In [ ]:
efficiency = production_array / area_array
print("Production Efficiency (first 5):", efficiency[:5])

Production Efficiency (first 5): [7.68255345e-01 7.05891216e-01 2.76381910e-02 6.45629833e+03
 4.56584244e-01]


In [ ]:
high_yield = yield_array[yield_array > np.mean(yield_array)]
print("High Yield Values:", high_yield[:10])

High Yield Values: [ 5238.051739  5376.054286 13003.78778   6045.886957  4867.65
  4692.261111  5304.749286 12448.06222   5672.116522  4868.07    ]


In [ ]:
index = np.argmax(yield_array)
print("Best Yield Index:", index)
print("Best Yield Value:", yield_array[index])

Best Yield Index: 442
Best Yield Value: 13592.12778


In [ ]:
print("25% Yield:", np.percentile(yield_array, 25))
print("50% Yield (Median):", np.percentile(yield_array, 50))
print("75% Yield:", np.percentile(yield_array, 75))

25% Yield: 0.5495833330000001
50% Yield (Median): 1.0563975155
75% Yield: 2.9218055555


In [ ]:
#Matplotlib
import matplotlib.pyplot as plt

In [ ]:
df = df.dropna()   # remove missing values
print(df)

              Crop  Year       Season           State    Area  Production  \
0         Arecanut  1997  Whole Year            Assam   73814       56708   
1        Arhar/Tur  1997  Kharif                Assam    6637        4685   
2      Castor seed  1997  Kharif                Assam     796          22   
3         Coconut   1997  Whole Year            Assam   19656   126905000   
4     Cotton(lint)  1997  Kharif                Assam    1739         794   
...            ...   ...          ...             ...     ...         ...   
1985     Arhar/Tur  2006  Kharif       Andhra Pradesh  395644      157669   
1986     Arhar/Tur  2006  Rabi         Andhra Pradesh    5606        3174   
1987         Bajra  2006  Kharif       Andhra Pradesh   48995       39988   
1988         Bajra  2006  Rabi         Andhra Pradesh   12081        6986   
1989        Banana  2006  Whole Year   Andhra Pradesh   50286     1224106   

      Annual_Rainfall   Fertilizer  Pesticide        Yield  
0             

In [ ]:
df.fillna(0, inplace=True)
print(df)

              Crop  Year       Season           State    Area  Production  \
0         Arecanut  1997  Whole Year            Assam   73814       56708   
1        Arhar/Tur  1997  Kharif                Assam    6637        4685   
2      Castor seed  1997  Kharif                Assam     796          22   
3         Coconut   1997  Whole Year            Assam   19656   126905000   
4     Cotton(lint)  1997  Kharif                Assam    1739         794   
...            ...   ...          ...             ...     ...         ...   
1985     Arhar/Tur  2006  Kharif       Andhra Pradesh  395644      157669   
1986     Arhar/Tur  2006  Rabi         Andhra Pradesh    5606        3174   
1987         Bajra  2006  Kharif       Andhra Pradesh   48995       39988   
1988         Bajra  2006  Rabi         Andhra Pradesh   12081        6986   
1989        Banana  2006  Whole Year   Andhra Pradesh   50286     1224106   

      Annual_Rainfall   Fertilizer  Pesticide        Yield  
0             

In [ ]:
year = df['Year']
production = df['Production']
rainfall = df['Annual_Rainfall']
print(year)
print(production)
print(rainfall)

0       1997
1       1997
2       1997
3       1997
4       1997
        ... 
1985    2006
1986    2006
1987    2006
1988    2006
1989    2006
Name: Year, Length: 1990, dtype: int64
0           56708
1            4685
2              22
3       126905000
4             794
          ...    
1985       157669
1986         3174
1987        39988
1988         6986
1989      1224106
Name: Production, Length: 1990, dtype: int64
0       2051.4
1       2051.4
2       2051.4
3       2051.4
4       2051.4
         ...  
1985     845.2
1986     845.2
1987     845.2
1988     845.2
1989     845.2
Name: Annual_Rainfall, Length: 1990, dtype: float64
